"""Initial schema — leads, lead_notes, admin_users, mv_monthly_rollup.

Written as raw SQL rather than autogenerated from ORM metadata: this DDL is
copied verbatim from Tech Spec §3 (the source of truth for schema), and
includes enum types, a trigger, and a materialized view — none of which
autogenerate reliably from SQLAlchemy models.

Revision ID: 0001_initial_schema
Revises:
Create Date: 2026-07-16
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op

revision: str = "0001_initial_schema"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute(
        """
        CREATE TYPE lead_source AS ENUM (
            'hero_quote_form', 'cta_quote_form', 'residential_valuation',
            'commercial_valuation', 'rural_valuation'
        );
        """
    )
    op.execute(
        """
        CREATE TYPE lead_status AS ENUM (
            'new', 'contacted', 'qualified', 'converted', 'lost'
        );
        """
    )

    op.execute(
        """
        CREATE TABLE leads (
            id                BIGSERIAL PRIMARY KEY,
            source            lead_source NOT NULL,
            first_name        VARCHAR(100),
            last_name         VARCHAR(100),
            email             VARCHAR(255) NOT NULL,
            phone             VARCHAR(50),
            property_address  TEXT,
            property_type     VARCHAR(100),
            purpose           VARCHAR(100),
            status            lead_status NOT NULL DEFAULT 'new',
            assigned_to       VARCHAR(100),
            page_url          VARCHAR(500),
            ip_address        VARCHAR(45),
            created_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
            updated_at        TIMESTAMPTZ NOT NULL DEFAULT now()
        );
        """
    )
    op.execute("CREATE INDEX idx_leads_status ON leads(status);")
    op.execute("CREATE INDEX idx_leads_email ON leads(email);")
    op.execute("CREATE INDEX idx_leads_created_at ON leads(created_at DESC);")
    op.execute("CREATE INDEX idx_leads_source ON leads(source);")
    op.execute("CREATE INDEX idx_leads_assigned_to ON leads(assigned_to);")

    op.execute(
        """
        CREATE TABLE lead_notes (
            id          BIGSERIAL PRIMARY KEY,
            lead_id     BIGINT NOT NULL REFERENCES leads(id) ON DELETE CASCADE,
            author      VARCHAR(100) NOT NULL,
            note        TEXT NOT NULL,
            created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
        );
        """
    )
    # Every FK has an index (Engineering Rules §4).
    op.execute("CREATE INDEX idx_lead_notes_lead_id ON lead_notes(lead_id);")

    op.execute(
        """
        CREATE TABLE admin_users (
            id              BIGSERIAL PRIMARY KEY,
            username        VARCHAR(100) NOT NULL UNIQUE,
            email           VARCHAR(255) NOT NULL UNIQUE,
            hashed_password VARCHAR(255) NOT NULL,
            role            VARCHAR(20) NOT NULL DEFAULT 'staff' CHECK (role IN ('admin', 'staff')),
            created_at      TIMESTAMPTZ NOT NULL DEFAULT now()
        );
        """
    )

    op.execute(
        """
        CREATE OR REPLACE FUNCTION set_updated_at() RETURNS TRIGGER AS $$
        BEGIN
          NEW.updated_at = now();
          RETURN NEW;
        END;
        $$ LANGUAGE plpgsql;
        """
    )
    op.execute(
        """
        CREATE TRIGGER trg_leads_updated_at
        BEFORE UPDATE ON leads
        FOR EACH ROW EXECUTE FUNCTION set_updated_at();
        """
    )

    op.execute(
        """
        CREATE MATERIALIZED VIEW mv_monthly_rollup AS
        SELECT
          date_trunc('month', created_at) AS month,
          property_type,
          purpose,
          count(*) AS total,
          count(*) FILTER (WHERE status = 'converted') AS converted_count
        FROM leads
        GROUP BY 1, 2, 3;
        """
    )
    # Trigger-based refresh (Tech Spec §6, Open Decision #3 recommendation) —
    # the dashboard must never drift from the underlying table.
    op.execute(
        """
        CREATE OR REPLACE FUNCTION refresh_mv_monthly_rollup() RETURNS TRIGGER AS $$
        BEGIN
          REFRESH MATERIALIZED VIEW mv_monthly_rollup;
          RETURN NULL;
        END;
        $$ LANGUAGE plpgsql;
        """
    )
    op.execute(
        """
        CREATE TRIGGER trg_refresh_mv_monthly_rollup
        AFTER INSERT OR UPDATE OR DELETE ON leads
        FOR EACH STATEMENT EXECUTE FUNCTION refresh_mv_monthly_rollup();
        """
    )

    # RLS enabled with no policies yet = deny-by-default for all non-owner
    # access. Actual policies are a separate, reviewed migration once the RLS
    # identity-mapping open decision (Tech Spec §6.1) is implemented — this is
    # a launch blocker (Engineering Rules §3), not something to stub out here.
    op.execute("ALTER TABLE leads ENABLE ROW LEVEL SECURITY;")
    op.execute("ALTER TABLE lead_notes ENABLE ROW LEVEL SECURITY;")


def downgrade() -> None:
    op.execute("DROP TRIGGER IF EXISTS trg_refresh_mv_monthly_rollup ON leads;")
    op.execute("DROP FUNCTION IF EXISTS refresh_mv_monthly_rollup();")
    op.execute("DROP MATERIALIZED VIEW IF EXISTS mv_monthly_rollup;")
    op.execute("DROP TRIGGER IF EXISTS trg_leads_updated_at ON leads;")
    op.execute("DROP FUNCTION IF EXISTS set_updated_at();")
    op.execute("DROP TABLE IF EXISTS admin_users;")
    op.execute("DROP TABLE IF EXISTS lead_notes;")
    op.execute("DROP TABLE IF EXISTS leads;")
    op.execute("DROP TYPE IF EXISTS lead_status;")
    op.execute("DROP TYPE IF EXISTS lead_source;")
